[project]
name = "dlr-tictac"
version = "1.0.0"
description = "My first Python project"
requires-python = ">=3.8"
authors = [
	{name = "celia baumhoer", email = "cb@dlr.de"}
]

dependencies = [
	"numpy",
	"pandas",
]
